### ISSUE TITLE
Unable to resolve media type for specifier for `ipfs-http-client@52.0.3-rc.8`

### ISSUE THREAD

**Issue by talentlessguy** [alephjs/esm.sh#110]
hey, yet another bug report

when trying to import `ipfs-http-client` like this:

```ts
import { create } from 'https://esm.sh/ipfs-http-client@52.0.3-rc.8'
```

I get this

```
Download https://cdn.esm.sh/v47/ipfs-http-client@52.0.3-rc.8+c4f96fac/dist/src/index.d.ts
Check file:///home/v1rtl/Coding/space.land/cli/space.ts
error: Error: Unable to resolve media type for specifier: "https://cdn.esm.sh/v47/ipfs-http-client@52.0.3-rc.8+c4f96fac/dist/src/index.d.ts"
    at deno:core/01_core.js:106:46
    at unwrapOpResult (deno:core/01_core.js:126:13)
    at Object.opSync (deno:core/01_core.js:140:12)
    at Object.resolveModuleNames (deno:cli/tsc/99_main_compiler.js:343:29)
    at actualResolveModuleNamesWorker (deno:cli/tsc/00_typescript.js:109500:133)
    at resolveModuleNamesWorker (deno:cli/tsc/00_typescript.js:109763:26)
    at resolveModuleNamesReusingOldState (deno:cli/tsc/00_typescript.js:109860:24)
    at processImportedModules (deno:cli/tsc/00_typescript.js:111315:35)
    at findSourceFileWorker (deno:cli/tsc/00_typescript.js:111116:17)
    at findSourceFile (deno:cli/tsc/00_typescript.js:110977:26)
```

Related: #109

**Comment by talentlessguy** [comment]
now I get this:

```ts
import { create } from 'https://esm.sh/ipfs-http-client@52.0.3'
```

```
error: TS2439 [ERROR]: Import or export declaration in an ambient module declaration cannot reference module through relative module name.
    import * as stream from '/v48/@types/node@14.17.15/stream.d.ts';
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    at https://cdn.esm.sh/v48/@types/node@14.17.15/http.d.ts:2:5

TS2439 [ERROR]: Import or export declaration in an ambient module declaration cannot reference module through relative module name.
    import { URL } from '/v48/@types/node@14.17.15/url.d.ts';
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    at https://cdn.esm.sh/v48/@types/node@14.17.15/http.d.ts:3:5

TS2439 [ERROR]: Import or export declaration in an ambient module declaration cannot reference module through relative module name.
    import { Socket, Server as NetServer } from '/v48/@types/node@14.17.15/net.d.ts';
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    at https://cdn.esm.sh/v48/@types/node@14.17.15/http.d.ts:4:5

TS2439 [ERROR]: Import or export declaration in an ambient module declaration cannot reference module through relative module name.
    import { Duplex } from '/v48/@types/node@14.17.15/stream.d.ts';
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    at https://cdn.esm.sh/v48/@types/node@14.17.15/https.d.ts:2:5

TS2439 [ERROR]: Import or export declaration in an ambient module declaration cannot reference module through relative module name.
    import * as tls from '/v48/@types/node@14.17.15/tls.d.ts';
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    at https://cdn.esm.sh/v48/@types/node@14.17.15/https.d.ts:3:5

TS2439 [ERROR]: Import or export declaration in an ambient module declaration cannot reference module through relative module name.
    import * as http from '/v48/@types/node@14.17.15/http.d.ts';
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    at https://cdn.esm.sh/v48/@types/node@14.17.15/https.d.ts:4:5

TS2439 [ERROR]: Import or export declaration in an ambient module declaration cannot reference module through relative module name.
    import { URL } from '/v48/@types/node@14.17.15/url.d.ts';
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    at https://cdn.esm.sh/v48/@types/node@14.17.15/https.d.ts:5:5

TS2305 [ERROR]: Module '"deno:///missing_dependency.d.ts"' has no exported member 'CID'.
import type { CID } from '/v48/multiformats@9.4.7/cid.d.ts';
              ~~~
    at https://cdn.esm.sh/v48/ipfs-core-types@0.7.1/dist/src/utils.d.ts:1:15

TS2305 [ERROR]: Module '"deno:///missing_dependency.d.ts"' has no exported member 'CID'.
import type { CID, CIDVersion } from '/v48/multiformats@9.4.7/cid.d.ts';
              ~~~
    at https://cdn.esm.sh/v48/ipfs-core-types@0.7.1/dist/src/root.d.ts:2:15

TS2305 [ERROR]: Module '"deno:///missing_dependency.d.ts"' has no exported member 'CIDVersion'.
import type { CID, CIDVersion } from '/v48/multiformats@9.4.7/cid.d.ts';
                   ~~~~~~~~~~
    at https://cdn.esm.sh/v48/ipfs-core-types@0.7.1/dist/src/root.d.ts:2:20

TS2305 [ERROR]: Module '"deno:///missing_dependency.d.ts"' has no exported member 'CID'.
import type { CID } from '/v48/multiformats@9.4.7/cid.d.ts';
              ~~~
    at https://cdn.esm.sh/v48/ipfs-core-types@0.7.1/dist/src/bitswap/index.d.ts:1:15

TS2305 [ERROR]: Module '"deno:///missing_dependency.d.ts"' has no exported member 'CID'.
import type { CID, CIDVersion } from '/v48/multiformats@9.4.7/cid.d.ts';
              ~~~
    at https://cdn.esm.sh/v48/ipfs-core-types@0.7.1/dist/src/block/index.d.ts:2:15

TS2305 [ERROR]: Module '"deno:///missing_dependency.d.ts"' has no exported member 'CIDVersion'.
import type { CID, CIDVersion } from '/v48/multiformats@9.4.7/cid.d.ts';
                   ~~~~~~~~~~
    at https://cdn.esm.sh/v48/ipfs-core-types@0.7.1/dist/src/block/index.d.ts:2:20

TS2305 [ERROR]: Module '"deno:///missing_dependency.d.ts"' has no exported member 'CID'.
import type { CID, CIDVersion } from '/v48/multiformats@9.4.7/cid.d.ts';
              ~~~
    at https://cdn.esm.sh/v48/ipfs-core-types@0.7.1/dist/src/dag/index.d.ts:2:15

TS2305 [ERROR]: Module '"deno:///missing_dependency.d.ts"' has no exported member 'CIDVersion'.
import type { CID, CIDVersion } from '/v48/multiformats@9.4.7/cid.d.ts';
                   ~~~~~~~~~~
    at https://cdn.esm.sh/v48/ipfs-core-types@0.7.1/dist/src/dag/index.d.ts:2:20

TS2305 [ERROR]: Module '"deno:///missing_dependency.d.ts"' has no exported member 'CID'.
import type { CID } from '/v48/multiformats@9.4.7/cid.d.ts';
              ~~~
    at https://cdn.esm.sh/v48/ipfs-core-types@0.7.1/dist/src/dht/index.d.ts:3:15

TS2305 [ERROR]: Module '"deno:///missing_dependency.d.ts"' has no exported member 'CID'.
import type { CID, CIDVersion } from '/v48/multiformats@9.4.7/cid.d.ts';
              ~~~
    at https://cdn.esm.sh/v48/ipfs-core-types@0.7.1/dist/src/files/index.d.ts:2:15

TS2305 [ERROR]: Module '"deno:///missing_dependency.d.ts"' has no exported member 'CIDVersion'.
import type { CID, CIDVersion } from '/v48/multiformats@9.4.7/cid.d.ts';
                   ~~~~~~~~~~
    at https://cdn.esm.sh/v48/ipfs-core-types@0.7.1/dist/src/files/index.d.ts:2:20

TS2305 [ERROR]: Module '"deno:///missing_dependency.d.ts"' has no exported member 'CID'.
import type { CID } from '/v48/multiformats@9.4.7/cid.d.ts';
              ~~~
    at https://cdn.esm.sh/v48/ipfs-core-types@0.7.1/dist/src/name/index.d.ts:1:15

TS2305 [ERROR]: Module '"deno:///missing_dependency.d.ts"' has no exported member 'CID'.
import { CID } from '/v48/multiformats@9.4.7/cid.d.ts';
         ~~~
    at https://cdn.esm.sh/v48/@ipld/dag-pb@2.1.9/types/src/interface.d.ts:1:10

TS2305 [ERROR]: Module '"deno:///missing_dependency.d.ts"' has no exported member 'CID'.
import { CID } from "/v48/multiformats@9.4.7/cid.d.ts";
         ~~~
    at https://cdn.esm.sh/v48/@ipld/dag-pb@2.1.9/types/src/util.d.ts:25:10

TS2694 [ERROR]: Namespace '__' has no exported member 'ByteView'.
export type ByteView<T> = import('/v48/multiformats@9.4.7/codecs/interface.d.ts').ByteView<T>;
                                                                                  ~~~~~~~~
    at https://cdn.esm.sh/v48/@ipld/dag-pb@2.1.9/types/src/index.d.ts:21:83

TS2305 [ERROR]: Module '"deno:///missing_dependency.d.ts"' has no exported member 'CID'.
import type { CID } from '/v48/multiformats@9.4.7/cid.d.ts';
              ~~~
    at https://cdn.esm.sh/v48/ipfs-core-types@0.7.1/dist/src/object/patch/index.d.ts:1:15

TS2305 [ERROR]: Module '"deno:///missing_dependency.d.ts"' has no exported member 'CID'.
import type { CID } from '/v48/multiformats@9.4.7/cid.d.ts';
              ~~~
    at https://cdn.esm.sh/v48/ipfs-core-types@0.7.1/dist/src/object/index.d.ts:1:15

TS2305 [ERROR]: Module '"deno:///missing_dependency.d.ts"' has no exported member 'CID'.
import type { CID } from '/v48/multiformats@9.4.7/cid.d.ts';
              ~~~
    at https://cdn.esm.sh/v48/ipfs-core-types@0.7.1/dist/src/pin/remote/index.d.ts:1:15

TS2305 [ERROR]: Module '"deno:///missing_dependency.d.ts"' has no exported member 'CID'.
import type { CID } from '/v48/multiformats@9.4.7/cid.d.ts';
              ~~~
    at https://cdn.esm.sh/v48/ipfs-core-types@0.7.1/dist/src/pin/index.d.ts:2:15

TS2305 [ERROR]: Module '"deno:///missing_dependency.d.ts"' has no exported member 'CID'.
import type { CID } from '/v48/multiformats@9.4.7/cid.d.ts';
              ~~~
    at https://cdn.esm.sh/v48/ipfs-core-types@0.7.1/dist/src/repo/index.d.ts:2:15

TS2305 [ERROR]: Module '"deno:///missing_dependency.d.ts"' has no exported member 'BlockCodec'.
import type { BlockCodec } from '/v48/multiformats@9.4.7/codecs/interface.d.ts';
              ~~~~~~~~~~
    at https://cdn.esm.sh/v48/ipfs-core-types@0.7.1/dist/src/index.d.ts:21:15

TS2305 [ERROR]: Module '"deno:///missing_dependency.d.ts"' has no exported member 'MultibaseCodec'.
import type { MultibaseCodec } from '/v48/multiformats@9.4.7/bases/interface.d.ts';
              ~~~~~~~~~~~~~~
    at https://cdn.esm.sh/v48/ipfs-core-types@0.7.1/dist/src/index.d.ts:22:15

TS2305 [ERROR]: Module '"deno:///missing_dependency.d.ts"' has no exported member 'MultihashHasher'.
import type { MultihashHasher } from '/v48/multiformats@9.4.7/hashes/interface.d.ts';
              ~~~~~~~~~~~~~~~
    at https://cdn.esm.sh/v48/ipfs-core-types@0.7.1/dist/src/index.d.ts:23:15

TS2305 [ERROR]: Module '"deno:///missing_dependency.d.ts"' has no exported member 'BlockCodec'.
import type { BlockCodec } from '/v48/multiformats@9.4.7/codecs/interface.d.ts';
              ~~~~~~~~~~
    at https://cdn.esm.sh/v48/ipfs-http-client@52.0.3/dist/src/types.d.ts:5:15

TS2305 [ERROR]: Module '"deno:///missing_dependency.d.ts"' has no exported member 'MultihashHasher'.
import type { MultihashHasher } from '/v48/multiformats@9.4.7/hashes/interface.d.ts';
              ~~~~~~~~~~~~~~~
    at https://cdn.esm.sh/v48/ipfs-http-client@52.0.3/dist/src/types.d.ts:6:15

TS2305 [ERROR]: Module '"deno:///missing_dependency.d.ts"' has no exported member 'MultibaseCodec'.
import type { MultibaseCodec } from '/v48/multiformats@9.4.7/bases/interface.d.ts';
              ~~~~~~~~~~~~~~
    at https://cdn.esm.sh/v48/ipfs-http-client@52.0.3/dist/src/types.d.ts:7:15

TS2694 [ERROR]: Namespace '__' has no exported member 'BlockCodec'.
export type BlockCodec = import('/v48/multiformats@9.4.7/codecs/interface.d.ts').BlockCodec<any, any>;
                                                                                 ~~~~~~~~~~
    at https://cdn.esm.sh/v48/ipfs-http-client@52.0.3/dist/src/index.d.ts:3:82

TS2694 [ERROR]: Namespace '__' has no exported member 'MultihashHasher'.
export type MultihashHasher = import('/v48/multiformats@9.4.7/hashes/interface.d.ts').MultihashHasher;
                                                                                      ~~~~~~~~~~~~~~~
    at https://cdn.esm.sh/v48/ipfs-http-client@52.0.3/dist/src/index.d.ts:4:87

TS2694 [ERROR]: Namespace '__' has no exported member 'MultibaseCodec'.
export type MultibaseCodec = import('/v48/multiformats@9.4.7/bases/interface.d.ts').MultibaseCodec<any>;
                                                                                    ~~~~~~~~~~~~~~
    at https://cdn.esm.sh/v48/ipfs-http-client@52.0.3/dist/src/index.d.ts:5:85

TS2305 [ERROR]: Module '"deno:///missing_dependency.d.ts"' has no exported member 'CID'.
import { CID } from "/v48/multiformats@9.4.7/cid.d.ts";
         ~~~
    at https://cdn.esm.sh/v48/ipfs-http-client@52.0.3/dist/src/index.d.ts:19:10

Found 37 errors.
```

**Comment by talentlessguy** [comment]
with v50 I get this now:

```
➜ deno run deno.ts
Download https://cdn.esm.sh/ipfs-http-client@52.0.3/dist/src/types
Check file:///tmp/deno.ts
error: TS2694 [ERROR]: Namespace '__' has no exported member 'EndpointConfig'.
export type EndpointConfig = import('./types').EndpointConfig;
                                               ~~~~~~~~~~~~~~
    at https://cdn.esm.sh/ipfs-http-client@52.0.3/dist/src/index.d.ts:1:48

TS2694 [ERROR]: Namespace '__' has no exported member 'Options'.
export type Options = import('./types').Options;
                                        ~~~~~~~
    at https://cdn.esm.sh/ipfs-http-client@52.0.3/dist/src/index.d.ts:2:41

TS2694 [ERROR]: Namespace '__' has no exported member 'BlockCodec'.
export type BlockCodec = import('multiformats/codecs/interface').BlockCodec<any, any>;
                                                                 ~~~~~~~~~~
    at https://cdn.esm.sh/ipfs-http-client@52.0.3/dist/src/index.d.ts:3:66

TS2694 [ERROR]: Namespace '__' has no exported member 'MultihashHasher'.
export type MultihashHasher = import('multiformats/hashes/interface').MultihashHasher;
                                                                      ~~~~~~~~~~~~~~~
    at https://cdn.esm.sh/ipfs-http-client@52.0.3/dist/src/index.d.ts:4:71

TS2694 [ERROR]: Namespace '__' has no exported member 'MultibaseCodec'.
export type MultibaseCodec = import('multiformats/bases/interface').MultibaseCodec<any>;
                                                                    ~~~~~~~~~~~~~~
    at https://cdn.esm.sh/ipfs-http-client@52.0.3/dist/src/index.d.ts:5:69

TS2694 [ERROR]: Namespace '__' has no exported member 'IPFSHTTPClient'.
export type IPFSHTTPClient = import('./types').IPFSHTTPClient;
                                               ~~~~~~~~~~~~~~
    at https://cdn.esm.sh/ipfs-http-client@52.0.3/dist/src/index.d.ts:6:48

TS2694 [ERROR]: Namespace '__' has no exported member 'IPFSHTTPClient'.
export function create(options?: Options): import("./types").IPFSHTTPClient;
                                                             ~~~~~~~~~~~~~~
    at https://cdn.esm.sh/ipfs-http-client@52.0.3/dist/src/index.d.ts:18:62

TS2305 [ERROR]: Module '"deno:///missing_dependency.d.ts"' has no exported member 'CID'.
import { CID } from "multiformats/cid";
         ~~~
    at https://cdn.esm.sh/ipfs-http-client@52.0.3/dist/src/index.d.ts:19:10

TS2305 [ERROR]: Module '"deno:///missing_dependency.d.ts"' has no exported member 'multiaddr'.
import { multiaddr } from "multiaddr";
         ~~~~~~~~~
    at https://cdn.esm.sh/ipfs-http-client@52.0.3/dist/src/index.d.ts:20:10

Found 9 errors.
```
