### ISSUE TITLE
Failed to import - astring

### ISSUE THREAD

**Issue by talentlessguy** [alephjs/esm.sh#114]
## Failing module

- **GitHub**: https://github.com/davidbonnet/astring
- **npm**: https://npmjs.org/package/astring

```js
import * as mod from 'https://esm.sh/astring'
```

## Error message

After running `deno run` I get this:

```
Download https://esm.sh/astring
Download https://cdn.esm.sh/v47/@types/source-map@0.5.7/index.d.ts
Download https://cdn.esm.sh/v47/node:events
Download https://cdn.esm.sh/v47/node:stream/consumers
Download https://cdn.esm.sh/v47/node:stream/promises
Check file:///tmp/test.ts
error: TS2439 [ERROR]: Import or export declaration in an ambient module declaration cannot reference module through relative module name.
    import { EventEmitter, Abortable } from '/v47/node:events';
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    at https://cdn.esm.sh/v47/@types/node@16.7.10/stream.d.ts:20:5

TS2439 [ERROR]: Import or export declaration in an ambient module declaration cannot reference module through relative module name.
    import * as streamPromises from '/v47/node:stream/promises';
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    at https://cdn.esm.sh/v47/@types/node@16.7.10/stream.d.ts:21:5

TS2439 [ERROR]: Import or export declaration in an ambient module declaration cannot reference module through relative module name.
    import * as streamConsumers from '/v47/node:stream/consumers';
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    at https://cdn.esm.sh/v47/@types/node@16.7.10/stream.d.ts:22:5

TS2503 [ERROR]: Cannot find namespace 'NodeJS'.
        pipe<T extends NodeJS.WritableStream>(
                       ~~~~~~
    at https://cdn.esm.sh/v47/@types/node@16.7.10/stream.d.ts:24:24

TS2304 [ERROR]: Cannot find name 'BufferEncoding'.
            encoding?: BufferEncoding | undefined;
                       ~~~~~~~~~~~~~~
    at https://cdn.esm.sh/v47/@types/node@16.7.10/stream.d.ts:44:24

TS2503 [ERROR]: Cannot find namespace 'NodeJS'.
        class Readable extends Stream implements NodeJS.ReadableStream {
                                                 ~~~~~~
    at https://cdn.esm.sh/v47/@types/node@16.7.10/stream.d.ts:50:50

TS2304 [ERROR]: Cannot find name 'BufferEncoding'.
            readonly readableEncoding: BufferEncoding | null;
                                       ~~~~~~~~~~~~~~
    at https://cdn.esm.sh/v47/@types/node@16.7.10/stream.d.ts:65:40

TS2304 [ERROR]: Cannot find name 'BufferEncoding'.
            setEncoding(encoding: BufferEncoding): this;
                                  ~~~~~~~~~~~~~~
    at https://cdn.esm.sh/v47/@types/node@16.7.10/stream.d.ts:203:35

TS2503 [ERROR]: Cannot find namespace 'NodeJS'.
            unpipe(destination?: NodeJS.WritableStream): this;
                                 ~~~~~~
    at https://cdn.esm.sh/v47/@types/node@16.7.10/stream.d.ts:288:34

TS2304 [ERROR]: Cannot find name 'BufferEncoding'.
            unshift(chunk: any, encoding?: BufferEncoding): void;
                                           ~~~~~~~~~~~~~~
    at https://cdn.esm.sh/v47/@types/node@16.7.10/stream.d.ts:354:44

TS2503 [ERROR]: Cannot find namespace 'NodeJS'.
            wrap(stream: NodeJS.ReadableStream): this;
                         ~~~~~~
    at https://cdn.esm.sh/v47/@types/node@16.7.10/stream.d.ts:380:26

TS2304 [ERROR]: Cannot find name 'BufferEncoding'.
            push(chunk: any, encoding?: BufferEncoding): boolean;
                                        ~~~~~~~~~~~~~~
    at https://cdn.esm.sh/v47/@types/node@16.7.10/stream.d.ts:381:41

TS2304 [ERROR]: Cannot find name 'BufferEncoding'.
            defaultEncoding?: BufferEncoding | undefined;
                              ~~~~~~~~~~~~~~
    at https://cdn.esm.sh/v47/@types/node@16.7.10/stream.d.ts:466:31

TS2304 [ERROR]: Cannot find name 'BufferEncoding'.
            write?(this: Writable, chunk: any, encoding: BufferEncoding, callback: (error?: Error | null) => void): void;
                                                         ~~~~~~~~~~~~~~
    at https://cdn.esm.sh/v47/@types/node@16.7.10/stream.d.ts:467:58

TS2304 [ERROR]: Cannot find name 'BufferEncoding'.
                    encoding: BufferEncoding;
                              ~~~~~~~~~~~~~~
    at https://cdn.esm.sh/v47/@types/node@16.7.10/stream.d.ts:472:31

TS2503 [ERROR]: Cannot find namespace 'NodeJS'.
        class Writable extends Stream implements NodeJS.WritableStream {
                                                 ~~~~~~
    at https://cdn.esm.sh/v47/@types/node@16.7.10/stream.d.ts:481:50

TS2304 [ERROR]: Cannot find name 'BufferEncoding'.
            _write(chunk: any, encoding: BufferEncoding, callback: (error?: Error | null) => void): void;
                                         ~~~~~~~~~~~~~~
    at https://cdn.esm.sh/v47/@types/node@16.7.10/stream.d.ts:528:42

TS2304 [ERROR]: Cannot find name 'BufferEncoding'.
                    encoding: BufferEncoding;
                              ~~~~~~~~~~~~~~
    at https://cdn.esm.sh/v47/@types/node@16.7.10/stream.d.ts:532:31

TS2304 [ERROR]: Cannot find name 'BufferEncoding'.
            write(chunk: any, encoding: BufferEncoding, callback?: (error: Error | null | undefined) => void): boolean;
                                        ~~~~~~~~~~~~~~
    at https://cdn.esm.sh/v47/@types/node@16.7.10/stream.d.ts:596:41

TS2304 [ERROR]: Cannot find name 'BufferEncoding'.
            setDefaultEncoding(encoding: BufferEncoding): this;
                                         ~~~~~~~~~~~~~~
    at https://cdn.esm.sh/v47/@types/node@16.7.10/stream.d.ts:602:42

TS2304 [ERROR]: Cannot find name 'BufferEncoding'.
            end(chunk: any, encoding: BufferEncoding, cb?: () => void): void;
                                      ~~~~~~~~~~~~~~
    at https://cdn.esm.sh/v47/@types/node@16.7.10/stream.d.ts:627:39

TS2304 [ERROR]: Cannot find name 'BufferEncoding'.
            write?(this: Duplex, chunk: any, encoding: BufferEncoding, callback: (error?: Error | null) => void): void;
                                                       ~~~~~~~~~~~~~~
    at https://cdn.esm.sh/v47/@types/node@16.7.10/stream.d.ts:763:56

TS2304 [ERROR]: Cannot find name 'BufferEncoding'.
                    encoding: BufferEncoding;
                              ~~~~~~~~~~~~~~
    at https://cdn.esm.sh/v47/@types/node@16.7.10/stream.d.ts:768:31

TS2304 [ERROR]: Cannot find name 'BufferEncoding'.
            _write(chunk: any, encoding: BufferEncoding, callback: (error?: Error | null) => void): void;
                                         ~~~~~~~~~~~~~~
    at https://cdn.esm.sh/v47/@types/node@16.7.10/stream.d.ts:795:42

TS2304 [ERROR]: Cannot find name 'BufferEncoding'.
                    encoding: BufferEncoding;
                              ~~~~~~~~~~~~~~
    at https://cdn.esm.sh/v47/@types/node@16.7.10/stream.d.ts:799:31

TS2304 [ERROR]: Cannot find name 'BufferEncoding'.
            write(chunk: any, encoding?: BufferEncoding, cb?: (error: Error | null | undefined) => void): boolean;
                                         ~~~~~~~~~~~~~~
    at https://cdn.esm.sh/v47/@types/node@16.7.10/stream.d.ts:805:42

TS2304 [ERROR]: Cannot find name 'BufferEncoding'.
            setDefaultEncoding(encoding: BufferEncoding): this;
                                         ~~~~~~~~~~~~~~
    at https://cdn.esm.sh/v47/@types/node@16.7.10/stream.d.ts:807:42

TS2304 [ERROR]: Cannot find name 'BufferEncoding'.
            end(chunk: any, encoding?: BufferEncoding, cb?: () => void): void;
                                       ~~~~~~~~~~~~~~
    at https://cdn.esm.sh/v47/@types/node@16.7.10/stream.d.ts:810:40

TS2304 [ERROR]: Cannot find name 'BufferEncoding'.
            write?(this: Transform, chunk: any, encoding: BufferEncoding, callback: (error?: Error | null) => void): void;
                                                          ~~~~~~~~~~~~~~
    at https://cdn.esm.sh/v47/@types/node@16.7.10/stream.d.ts:818:59

TS2304 [ERROR]: Cannot find name 'BufferEncoding'.
                    encoding: BufferEncoding;
                              ~~~~~~~~~~~~~~
    at https://cdn.esm.sh/v47/@types/node@16.7.10/stream.d.ts:823:31

TS2304 [ERROR]: Cannot find name 'BufferEncoding'.
            transform?(this: Transform, chunk: any, encoding: BufferEncoding, callback: TransformCallback): void;
                                                              ~~~~~~~~~~~~~~
    at https://cdn.esm.sh/v47/@types/node@16.7.10/stream.d.ts:829:63

TS2304 [ERROR]: Cannot find name 'BufferEncoding'.
            _transform(chunk: any, encoding: BufferEncoding, callback: TransformCallback): void;
                                             ~~~~~~~~~~~~~~
    at https://cdn.esm.sh/v47/@types/node@16.7.10/stream.d.ts:845:46

TS2503 [ERROR]: Cannot find namespace 'NodeJS'.
    at https://cdn.esm.sh/v47/@types/node@16.7.10/stream.d.ts:960:35

TS2503 [ERROR]: Cannot find namespace 'NodeJS'.
    at https://cdn.esm.sh/v47/@types/node@16.7.10/stream.d.ts:960:59

TS2503 [ERROR]: Cannot find namespace 'NodeJS'.
    at https://cdn.esm.sh/v47/@types/node@16.7.10/stream.d.ts:960:83

TS2503 [ERROR]: Cannot find namespace 'NodeJS'.
    at https://cdn.esm.sh/v47/@types/node@16.7.10/stream.d.ts:960:150

TS2503 [ERROR]: Cannot find namespace 'NodeJS'.
    at https://cdn.esm.sh/v47/@types/node@16.7.10/stream.d.ts:961:35

TS2503 [ERROR]: Cannot find namespace 'NodeJS'.
    at https://cdn.esm.sh/v47/@types/node@16.7.10/stream.d.ts:961:59

TS2503 [ERROR]: Cannot find namespace 'NodeJS'.
    at https://cdn.esm.sh/v47/@types/node@16.7.10/stream.d.ts:961:83

TS2503 [ERROR]: Cannot find namespace 'NodeJS'.
    at https://cdn.esm.sh/v47/@types/node@16.7.10/stream.d.ts:961:124

TS2503 [ERROR]: Cannot find namespace 'NodeJS'.
    at https://cdn.esm.sh/v47/@types/node@16.7.10/stream.d.ts:963:44

TS2503 [ERROR]: Cannot find namespace 'NodeJS'.
    at https://cdn.esm.sh/v47/@types/node@16.7.10/stream.d.ts:963:68

TS2503 [ERROR]: Cannot find namespace 'NodeJS'.
    at https://cdn.esm.sh/v47/@types/node@16.7.10/stream.d.ts:963:92

TS2503 [ERROR]: Cannot find namespace 'NodeJS'.
        type PipelineSource<T> = Iterable<T> | AsyncIterable<T> | NodeJS.ReadableStream | PipelineSourceFunction<T>;
                                                                  ~~~~~~
    at https://cdn.esm.sh/v47/@types/node@16.7.10/stream.d.ts:966:67

TS2503 [ERROR]: Cannot find namespace 'NodeJS'.
            | NodeJS.ReadWriteStream
              ~~~~~~
    at https://cdn.esm.sh/v47/@types/node@16.7.10/stream.d.ts:968:15

TS2503 [ERROR]: Cannot find namespace 'NodeJS'.
            ? NodeJS.WritableStream | PipelineDestinationIterableFunction<ST> | PipelineDestinationPromiseFunction<ST, P>
              ~~~~~~
    at https://cdn.esm.sh/v47/@types/node@16.7.10/stream.d.ts:974:15

TS2503 [ERROR]: Cannot find namespace 'NodeJS'.
            ? (err: NodeJS.ErrnoException | null, value: P) => void
                    ~~~~~~
    at https://cdn.esm.sh/v47/@types/node@16.7.10/stream.d.ts:977:21

TS2503 [ERROR]: Cannot find namespace 'NodeJS'.
            : (err: NodeJS.ErrnoException | null) => void;
                    ~~~~~~
    at https://cdn.esm.sh/v47/@types/node@16.7.10/stream.d.ts:978:21

TS2503 [ERROR]: Cannot find namespace 'NodeJS'.
        ): B extends NodeJS.WritableStream ? B : NodeJS.WritableStream;
                     ~~~~~~
    at https://cdn.esm.sh/v47/@types/node@16.7.10/stream.d.ts:1092:22

TS2503 [ERROR]: Cannot find namespace 'NodeJS'.
        ): B extends NodeJS.WritableStream ? B : NodeJS.WritableStream;
                                                 ~~~~~~
    at https://cdn.esm.sh/v47/@types/node@16.7.10/stream.d.ts:1092:50

TS2503 [ERROR]: Cannot find namespace 'NodeJS'.
        ): B extends NodeJS.WritableStream ? B : NodeJS.WritableStream;
                     ~~~~~~
    at https://cdn.esm.sh/v47/@types/node@16.7.10/stream.d.ts:1098:22

TS2503 [ERROR]: Cannot find namespace 'NodeJS'.
        ): B extends NodeJS.WritableStream ? B : NodeJS.WritableStream;
                                                 ~~~~~~
    at https://cdn.esm.sh/v47/@types/node@16.7.10/stream.d.ts:1098:50

TS2503 [ERROR]: Cannot find namespace 'NodeJS'.
        ): B extends NodeJS.WritableStream ? B : NodeJS.WritableStream;
                     ~~~~~~
    at https://cdn.esm.sh/v47/@types/node@16.7.10/stream.d.ts:1105:22

TS2503 [ERROR]: Cannot find namespace 'NodeJS'.
        ): B extends NodeJS.WritableStream ? B : NodeJS.WritableStream;
                                                 ~~~~~~
    at https://cdn.esm.sh/v47/@types/node@16.7.10/stream.d.ts:1105:50

TS2503 [ERROR]: Cannot find namespace 'NodeJS'.
    at https://cdn.esm.sh/v47/@types/node@16.7.10/stream.d.ts:1112:129

TS2503 [ERROR]: Cannot find namespace 'NodeJS'.
    at https://cdn.esm.sh/v47/@types/node@16.7.10/stream.d.ts:1112:157

TS2503 [ERROR]: Cannot find namespace 'NodeJS'.
    at https://cdn.esm.sh/v47/@types/node@16.7.10/stream.d.ts:1120:145

TS2503 [ERROR]: Cannot find namespace 'NodeJS'.
    at https://cdn.esm.sh/v47/@types/node@16.7.10/stream.d.ts:1120:173

TS2503 [ERROR]: Cannot find namespace 'NodeJS'.
            streams: ReadonlyArray<NodeJS.ReadableStream | NodeJS.WritableStream | NodeJS.ReadWriteStream>,
                                   ~~~~~~
    at https://cdn.esm.sh/v47/@types/node@16.7.10/stream.d.ts:1122:36

TS2503 [ERROR]: Cannot find namespace 'NodeJS'.
            streams: ReadonlyArray<NodeJS.ReadableStream | NodeJS.WritableStream | NodeJS.ReadWriteStream>,
                                                           ~~~~~~
    at https://cdn.esm.sh/v47/@types/node@16.7.10/stream.d.ts:1122:60

TS2503 [ERROR]: Cannot find namespace 'NodeJS'.
            streams: ReadonlyArray<NodeJS.ReadableStream | NodeJS.WritableStream | NodeJS.ReadWriteStream>,
                                                                                   ~~~~~~
    at https://cdn.esm.sh/v47/@types/node@16.7.10/stream.d.ts:1122:84

TS2503 [ERROR]: Cannot find namespace 'NodeJS'.
            callback?: (err: NodeJS.ErrnoException | null) => void
                             ~~~~~~
    at https://cdn.esm.sh/v47/@types/node@16.7.10/stream.d.ts:1123:30

TS2503 [ERROR]: Cannot find namespace 'NodeJS'.
        ): NodeJS.WritableStream;
           ~~~~~~
    at https://cdn.esm.sh/v47/@types/node@16.7.10/stream.d.ts:1124:12

TS2503 [ERROR]: Cannot find namespace 'NodeJS'.
            stream1: NodeJS.ReadableStream,
                     ~~~~~~
    at https://cdn.esm.sh/v47/@types/node@16.7.10/stream.d.ts:1126:22

TS2503 [ERROR]: Cannot find namespace 'NodeJS'.
            stream2: NodeJS.ReadWriteStream | NodeJS.WritableStream,
                     ~~~~~~
    at https://cdn.esm.sh/v47/@types/node@16.7.10/stream.d.ts:1127:22

TS2503 [ERROR]: Cannot find namespace 'NodeJS'.
            stream2: NodeJS.ReadWriteStream | NodeJS.WritableStream,
                                              ~~~~~~
    at https://cdn.esm.sh/v47/@types/node@16.7.10/stream.d.ts:1127:47

TS2503 [ERROR]: Cannot find namespace 'NodeJS'.
            ...streams: Array<NodeJS.ReadWriteStream | NodeJS.WritableStream | ((err: NodeJS.ErrnoException | null) => void)>
                              ~~~~~~
    at https://cdn.esm.sh/v47/@types/node@16.7.10/stream.d.ts:1128:31

TS2503 [ERROR]: Cannot find namespace 'NodeJS'.
            ...streams: Array<NodeJS.ReadWriteStream | NodeJS.WritableStream | ((err: NodeJS.ErrnoException | null) => void)>
                                                       ~~~~~~
    at https://cdn.esm.sh/v47/@types/node@16.7.10/stream.d.ts:1128:56

TS2503 [ERROR]: Cannot find namespace 'NodeJS'.
            ...streams: Array<NodeJS.ReadWriteStream | NodeJS.WritableStream | ((err: NodeJS.ErrnoException | null) => void)>
                                                                                      ~~~~~~
    at https://cdn.esm.sh/v47/@types/node@16.7.10/stream.d.ts:1128:87

TS2503 [ERROR]: Cannot find namespace 'NodeJS'.
        ): NodeJS.WritableStream;
           ~~~~~~
    at https://cdn.esm.sh/v47/@types/node@16.7.10/stream.d.ts:1129:12

TS2503 [ERROR]: Cannot find namespace 'NodeJS'.
    at https://cdn.esm.sh/v47/@types/node@16.7.10/stream.d.ts:1160:59

TS2503 [ERROR]: Cannot find namespace 'NodeJS'.
    at https://cdn.esm.sh/v47/@types/node@16.7.10/stream.d.ts:1160:83

TS2503 [ERROR]: Cannot find namespace 'NodeJS'.
    at https://cdn.esm.sh/v47/@types/node@16.7.10/stream.d.ts:1160:107

TS2503 [ERROR]: Cannot find namespace 'NodeJS'.
                stream1: NodeJS.ReadableStream,
                         ~~~~~~
    at https://cdn.esm.sh/v47/@types/node@16.7.10/stream.d.ts:1162:26

TS2503 [ERROR]: Cannot find namespace 'NodeJS'.
                stream2: NodeJS.ReadWriteStream | NodeJS.WritableStream,
                         ~~~~~~
    at https://cdn.esm.sh/v47/@types/node@16.7.10/stream.d.ts:1163:26

TS2503 [ERROR]: Cannot find namespace 'NodeJS'.
                stream2: NodeJS.ReadWriteStream | NodeJS.WritableStream,
                                                  ~~~~~~
    at https://cdn.esm.sh/v47/@types/node@16.7.10/stream.d.ts:1163:51

TS2503 [ERROR]: Cannot find namespace 'NodeJS'.
                ...streams: Array<NodeJS.ReadWriteStream | NodeJS.WritableStream | PipelineOptions>
                                  ~~~~~~
    at https://cdn.esm.sh/v47/@types/node@16.7.10/stream.d.ts:1164:35

TS2503 [ERROR]: Cannot find namespace 'NodeJS'.
                ...streams: Array<NodeJS.ReadWriteStream | NodeJS.WritableStream | PipelineOptions>
                                                           ~~~~~~
    at https://cdn.esm.sh/v47/@types/node@16.7.10/stream.d.ts:1164:60

TS2305 [ERROR]: Module '"deno:///missing_dependency.d.ts"' has no exported member 'Mapping'.
import type { Mapping, SourceMapGenerator } from '/v47/@types/source-map@0.5.7/index.d.ts'
              ~~~~~~~
    at https://cdn.esm.sh/v47/astring@1.7.5/astring.d.ts:2:15

TS2305 [ERROR]: Module '"deno:///missing_dependency.d.ts"' has no exported member 'SourceMapGenerator'.
import type { Mapping, SourceMapGenerator } from '/v47/@types/source-map@0.5.7/index.d.ts'
                       ~~~~~~~~~~~~~~~~~~
    at https://cdn.esm.sh/v47/astring@1.7.5/astring.d.ts:2:24

Found 80 errors.
```

## Additional info

- **esm.sh version**: v47
- **Deno version**: 1.13.2

**Comment by talentlessguy** [comment]
with `?deps=@types/source-map` I get this:

```
Download https://esm.sh/astring?deps=@types/source-map
Download https://cdn.esm.sh/v47/astring@1.7.5/X-ZGVwczpAdHlwZXMvc291cmNlLW1hcEAwLjUuNw/deno/astring.js
Download https://cdn.esm.sh/v47/X-ZGVwczpAdHlwZXMvc291cmNlLW1hcEAwLjUuNw/astring@1.7.5/astring.d.ts
Download https://cdn.esm.sh/v47/X-ZGVwczpAdHlwZXMvc291cmNlLW1hcEAwLjUuNw/@types/source-map@0.5.7/index.d.ts
Download https://cdn.esm.sh/v47/X-ZGVwczpAdHlwZXMvc291cmNlLW1hcEAwLjUuNw/@types/node/stream
Download https://cdn.esm.sh/v47/X-ZGVwczpAdHlwZXMvc291cmNlLW1hcEAwLjUuNw/@types/estree@0.0.50/index.d.ts
Check file:///tmp/test.ts
error: TS2305 [ERROR]: Module '"deno:///missing_dependency.d.ts"' has no exported member 'Mapping'.
import type { Mapping, SourceMapGenerator } from '/v47/X-ZGVwczpAdHlwZXMvc291cmNlLW1hcEAwLjUuNw/@types/source-map@0.5.7/index.d.ts'
              ~~~~~~~
    at https://cdn.esm.sh/v47/X-ZGVwczpAdHlwZXMvc291cmNlLW1hcEAwLjUuNw/astring@1.7.5/astring.d.ts:2:15

TS2305 [ERROR]: Module '"deno:///missing_dependency.d.ts"' has no exported member 'SourceMapGenerator'.
import type { Mapping, SourceMapGenerator } from '/v47/X-ZGVwczpAdHlwZXMvc291cmNlLW1hcEAwLjUuNw/@types/source-map@0.5.7/index.d.ts'
                       ~~~~~~~~~~~~~~~~~~
    at https://cdn.esm.sh/v47/X-ZGVwczpAdHlwZXMvc291cmNlLW1hcEAwLjUuNw/astring@1.7.5/astring.d.ts:2:24

TS2305 [ERROR]: Module '"deno:///missing_dependency.d.ts"' has no exported member 'Writable'.
import type { Writable } from '/v47/X-ZGVwczpAdHlwZXMvc291cmNlLW1hcEAwLjUuNw/@types/node/stream'
              ~~~~~~~~
    at https://cdn.esm.sh/v47/X-ZGVwczpAdHlwZXMvc291cmNlLW1hcEAwLjUuNw/astring@1.7.5/astring.d.ts:3:15

Found 3 errors.
```

**Comment by talentlessguy** [comment]
getting this with v49:

```
error: Error: Unable to resolve media type for specifier: "https://cdn.esm.sh/v49/astring@1.7.5/astring.d.ts"
    at deno:core/01_core.js:106:46
    at unwrapOpResult (deno:core/01_core.js:126:13)
    at Object.opSync (deno:core/01_core.js:140:12)
    at Object.resolveModuleNames (deno:cli/tsc/99_main_compiler.js:343:29)
    at actualResolveModuleNamesWorker (deno:cli/tsc/00_typescript.js:109500:133)
    at resolveModuleNamesWorker (deno:cli/tsc/00_typescript.js:109763:26)
    at resolveModuleNamesReusingOldState (deno:cli/tsc/00_typescript.js:109860:24)
    at processImportedModules (deno:cli/tsc/00_typescript.js:111315:35)
    at findSourceFileWorker (deno:cli/tsc/00_typescript.js:111116:17)
    at findSourceFile (deno:cli/tsc/00_typescript.js:110977:26)

```

**Comment by talentlessguy** [comment]
same as in #115 

```
error: Error: Unable to resolve media type for specifier: "https://cdn.esm.sh/v49/astring@1.7.5/astring.d.ts"
    at deno:core/01_core.js:106:46
    at unwrapOpResult (deno:core/01_core.js:126:13)
    at Object.opSync (deno:core/01_core.js:140:12)
    at Object.resolveModuleNames (deno:cli/tsc/99_main_compiler.js:343:29)
    at actualResolveModuleNamesWorker (deno:cli/tsc/00_typescript.js:109500:133)
    at resolveModuleNamesWorker (deno:cli/tsc/00_typescript.js:109763:26)
    at resolveModuleNamesReusingOldState (deno:cli/tsc/00_typescript.js:109860:24)
    at processImportedModules (deno:cli/tsc/00_typescript.js:111315:35)
    at findSourceFileWorker (deno:cli/tsc/00_typescript.js:111116:17)
    at findSourceFile (deno:cli/tsc/00_typescript.js:110977:26)
```

https://npmfs.com/package/astring/1.7.5/astring.d.ts

**Comment by ije** [comment]
@talentlessguy i figured out what happened

**Comment by ije** [comment]
a mistake here https://github.com/alephjs/esm.sh/blob/62e442f9ca879ef5398f72f292045ace38493404/server/pkg.go#L41

**Comment by talentlessguy** [comment]
@ije great that you found the root if this issue, hoping for this fix to be released soon

**Comment by talentlessguy** [comment]
Update, now getting this:

```
➜ deno cache -r deno.ts
Download https://esm.sh/astring
Download https://cdn.esm.sh/v47/astring@1.7.5/deno/astring.js
Download https://cdn.esm.sh/astring@1.7.5/astring.d.ts
Check file:///tmp/deno.ts
error: TS2305 [ERROR]: Module '"deno:///missing_dependency.d.ts"' has no exported member 'Node'.
import type { Node as EstreeNode } from 'estree'
              ~~~~
    at https://cdn.esm.sh/astring@1.7.5/astring.d.ts:1:15

TS2305 [ERROR]: Module '"deno:///missing_dependency.d.ts"' has no exported member 'Mapping'.
import type { Mapping, SourceMapGenerator } from 'source-map'
              ~~~~~~~
    at https://cdn.esm.sh/astring@1.7.5/astring.d.ts:2:15

TS2305 [ERROR]: Module '"deno:///missing_dependency.d.ts"' has no exported member 'SourceMapGenerator'.
import type { Mapping, SourceMapGenerator } from 'source-map'
                       ~~~~~~~~~~~~~~~~~~
    at https://cdn.esm.sh/astring@1.7.5/astring.d.ts:2:24

TS2305 [ERROR]: Module '"deno:///missing_dependency.d.ts"' has no exported member 'Writable'.
import type { Writable } from 'stream'
              ~~~~~~~~
    at https://cdn.esm.sh/astring@1.7.5/astring.d.ts:3:15

Found 4 errors.
```

**Comment by ije** [comment]
<img width="987" alt="Screenshot 2021-09-12 at 03 22 05" src="https://user-images.githubusercontent.com/2883484/132959176-2b1fd641-ab2c-4a6b-a8fa-5d2653a268ee.png">

**Comment by ije** [comment]
i just checked **v50** dts output, i will fix it ASAP

**Comment by talentlessguy** [comment]
nice, thx!

**Comment by ije** [comment]
fixed in v50

**Comment by talentlessguy** [comment]
not fixed, still errors:

```
Download https://esm.sh/astring
Download https://cdn.esm.sh/v47/astring@1.7.5/deno/astring.js
Download https://cdn.esm.sh/astring@1.7.5/astring.d.ts
Check file:///tmp/deno.ts
error: TS2305 [ERROR]: Module '"deno:///missing_dependency.d.ts"' has no exported member 'Node'.
import type { Node as EstreeNode } from 'estree'
              ~~~~
    at https://cdn.esm.sh/astring@1.7.5/astring.d.ts:1:15

TS2305 [ERROR]: Module '"deno:///missing_dependency.d.ts"' has no exported member 'Mapping'.
import type { Mapping, SourceMapGenerator } from 'source-map'
              ~~~~~~~
    at https://cdn.esm.sh/astring@1.7.5/astring.d.ts:2:15

TS2305 [ERROR]: Module '"deno:///missing_dependency.d.ts"' has no exported member 'SourceMapGenerator'.
import type { Mapping, SourceMapGenerator } from 'source-map'
                       ~~~~~~~~~~~~~~~~~~
    at https://cdn.esm.sh/astring@1.7.5/astring.d.ts:2:24

TS2305 [ERROR]: Module '"deno:///missing_dependency.d.ts"' has no exported member 'Writable'.
import type { Writable } from 'stream'
              ~~~~~~~~
    at https://cdn.esm.sh/astring@1.7.5/astring.d.ts:3:15

Found 4 errors.
```

**Comment by talentlessguy** [comment]
works with `https://esm.sh/astring?deps=estree` though
