### ISSUE TITLE
Failed to import - recharts

### ISSUE THREAD

**Issue by akaFTS** [alephjs/esm.sh#130]
## Failing module

- **GitHub**: https://github.com/recharts/recharts
- **npm**: https://www.npmjs.com/package/recharts

```js
import { Line } from "https://esm.sh/recharts@2.1.2";
```

## Error message

After running `deno run` I get this:

```
 > .aleph/production/-/cdn.esm.sh/v46/react-smooth@2.0.0/deno/react-smooth.bundling.js:925:9: error: No matching export in ".aleph/production/-/cdn.esm.sh/v46/react-transition-group@2.9.0/deno/react-transition-group.bundling.js" for import "TransitionGroup"
    925 │ import { TransitionGroup as Je } from "../../react-transition-group@2.9.0/deno/react-transition-group.bundling.js";
        ╵          ~~~~~~~~~~~~~~~

error: Uncaught (in promise) Error: Build failed with 1 error:
.aleph/production/-/cdn.esm.sh/v46/react-smooth@2.0.0/deno/react-smooth.bundling.js:925:9: error: No matching export in ".aleph/production/-/cdn.esm.sh/v46/react-transition-group@2.9.0/deno/react-transition-group.bundling.js" for import "TransitionGroup"
  let error = new Error(`${text}${summary}`);
              ^
    at failureErrorWithLog (https://deno.land/x/esbuild@v0.12.25/mod.js:1414:15)
    at https://deno.land/x/esbuild@v0.12.25/mod.js:1094:28
    at runOnEndCallbacks (https://deno.land/x/esbuild@v0.12.25/mod.js:882:63)
    at buildResponseToResult (https://deno.land/x/esbuild@v0.12.25/mod.js:1092:7)
    at https://deno.land/x/esbuild@v0.12.25/mod.js:1201:14
    at https://deno.land/x/esbuild@v0.12.25/mod.js:570:9
    at handleIncomingPacket (https://deno.land/x/esbuild@v0.12.25/mod.js:667:9)
    at readFromStdout (https://deno.land/x/esbuild@v0.12.25/mod.js:537:7)
    at https://deno.land/x/esbuild@v0.12.25/mod.js:1684:11
```

## Additional info

- **esm.sh version**: v46
- **Deno version**: 1.13.2

**Comment by talentlessguy** [comment]
Getting this on v50:

```
error: TS2304 [ERROR]: Cannot find name 'DOMRect'.
    onBBoxUpdate?: (box: DOMRect | null) => void;
                         ~~~~~~~
    at http://localhost:8080/v50/recharts@2.1.2/types/component/Legend.d.ts:17:26

TS2304 [ERROR]: Cannot find name 'DOMRect'.
    getBBox(): DOMRect;
               ~~~~~~~
    at http://localhost:8080/v50/recharts@2.1.2/types/component/Legend.d.ts:45:16

TS2304 [ERROR]: Cannot find name 'P'.
    at http://localhost:8080/v50/recharts@2.1.2/types/polar/Radar.d.ts:66:218

TS2304 [ERROR]: Cannot find name 'T'.
    at http://localhost:8080/v50/recharts@2.1.2/types/polar/Radar.d.ts:66:221

TS2304 [ERROR]: Cannot find name 'P'.
    at http://localhost:8080/v50/recharts@2.1.2/types/polar/Radar.d.ts:69:225

TS2304 [ERROR]: Cannot find name 'T'.
    at http://localhost:8080/v50/recharts@2.1.2/types/polar/Radar.d.ts:69:228

Found 6 errors.

```

**Comment by ije** [comment]
@akaFTS use `?no-check` may can help you, i will look into it later, thanks!

**Comment by akaFTS** [comment]
Seems to be working on v51, but I'll double-check tomorrow.

**Comment by akaFTS** [comment]
Confirmed to be working on the latest version.
