### ISSUE TITLE
Failed to import - preact/hooks types

### ISSUE THREAD

**Issue by yishn** [alephjs/esm.sh#149]
## Failing module

- **GitHub**: https://github.com/preactjs/preact
- **npm**: preact

```js
import { useState } from 'https://esm.sh/preact/hooks'
```

It seems like the `x-typescript-types` header sent by esm.sh are incorrect:

![image](https://user-images.githubusercontent.com/9217349/133589009-7933dd32-a3d6-4b6e-8008-ba85c0c44bf6.png)

It should be `https://cdn.esm.sh/v51/preact@10.5.14/hooks/src/index.d.ts` instead.

## Error message

After running `deno run` I get this:

```
error: Error: Unable to resolve media type for specifier: "https://cdn.esm.sh/v51/preact@10.5.13/hooks...d.ts"
    at deno:core/01_core.js:106:46
    at unwrapOpResult (deno:core/01_core.js:126:13)
    at Object.opSync (deno:core/01_core.js:140:12)
    at Object.resolveModuleNames (deno:cli/tsc/99_main_compiler.js:343:29)
    at actualResolveModuleNamesWorker (deno:cli/tsc/00_typescript.js:109500:133)
    at resolveModuleNamesWorker (deno:cli/tsc/00_typescript.js:109763:26)
    at resolveModuleNamesReusingOldState (deno:cli/tsc/00_typescript.js:109860:24)
    at processImportedModules (deno:cli/tsc/00_typescript.js:111315:35)
    at findSourceFileWorker (deno:cli/tsc/00_typescript.js:111116:17)
    at findSourceFile (deno:cli/tsc/00_typescript.js:110977:26)
```

## Additional info

- **esm.sh version**: v51
- **Deno version**: 1.13.2

**Comment by lucacasonato** [comment]
Having the same issue with `https://esm.sh/twind@0.16.16/sheets`

**Comment by ije** [comment]
fixed in v52, also added preact testing for deno: https://github.com/alephjs/esm.sh/tree/master/test/deno/preact
