### ISSUE TITLE
TS2503 [ERROR]: Cannot find namespace 'CSS'

### ISSUE THREAD

**Issue by 0x1af2aec8f957** [alephjs/esm.sh#152]
```bash
// test.ts
import styled from 'https://esm.sh/styled-components';

console.log(styled);
```
```bash
deno bundle test.ts 

Check file:///tmp/test.ts
error: TS2503 [ERROR]: Cannot find namespace 'CSS'.
export type CSSProperties = CSS.Properties<string | number>;
                            ~~~
    at https://cdn.esm.sh/@types/styled-components@5.1.14/index.d.ts:28:29

TS2503 [ERROR]: Cannot find namespace 'CSS'.
export type CSSPseudos = { [K in CSS.Pseudos]?: CSSObject };
                                 ~~~
    at https://cdn.esm.sh/@types/styled-components@5.1.14/index.d.ts:30:34

TS2430 [ERROR]: Interface 'CSSObject' incorrectly extends interface 'CSSPseudos'.
  'string' index signatures are incompatible.
    Type 'string | number | CSSObject | undefined' is not assignable to type 'CSSObject | undefined'.
      Type 'string' is not assignable to type 'CSSObject | undefined'.
export interface CSSObject extends CSSProperties, CSSPseudos {
                 ~~~~~~~~~
    at https://cdn.esm.sh/@types/styled-components@5.1.14/index.d.ts:32:18

TS2503 [ERROR]: Cannot find namespace 'JSX'.
export type IntrinsicElementsKeys = keyof JSX.IntrinsicElements;
                                          ~~~
    at https://cdn.esm.sh/@types/styled-components@5.1.14/index.d.ts:44:43

TS2503 [ERROR]: Cannot find namespace 'React'.
type MakeAttrsOptional<C extends string | React.ComponentType<any>, O extends object, A extends keyof any> = Omit<
                                          ~~~~~
    at https://cdn.esm.sh/@types/styled-components@5.1.14/index.d.ts:60:43

TS2503 [ERROR]: Cannot find namespace 'React'.
        React.ComponentPropsWithRef<C extends IntrinsicElementsKeys | React.ComponentType<any> ? C : never>
        ~~~~~
    at https://cdn.esm.sh/@types/styled-components@5.1.14/index.d.ts:63:9

TS2503 [ERROR]: Cannot find namespace 'React'.
        React.ComponentPropsWithRef<C extends IntrinsicElementsKeys | React.ComponentType<any> ? C : never>
                                                                      ~~~~~
    at https://cdn.esm.sh/@types/styled-components@5.1.14/index.d.ts:63:71

TS2503 [ERROR]: Cannot find namespace 'React'.
        Pick<React.ComponentPropsWithRef<C extends IntrinsicElementsKeys | React.ComponentType<any> ? C : never> & O, A>
             ~~~~~
    at https://cdn.esm.sh/@types/styled-components@5.1.14/index.d.ts:69:14

TS2503 [ERROR]: Cannot find namespace 'React'.
        Pick<React.ComponentPropsWithRef<C extends IntrinsicElementsKeys | React.ComponentType<any> ? C : never> & O, A>
                                                                           ~~~~~
    at https://cdn.esm.sh/@types/styled-components@5.1.14/index.d.ts:69:76

TS2503 [ERROR]: Cannot find namespace 'React'.
    C extends string | React.ComponentType<any>,
                       ~~~~~
    at https://cdn.esm.sh/@types/styled-components@5.1.14/index.d.ts:74:24

TS2503 [ERROR]: Cannot find namespace 'React'.
    FAsC extends string | React.ComponentType<any> = C
                          ~~~~~
    at https://cdn.esm.sh/@types/styled-components@5.1.14/index.d.ts:82:27

TS2503 [ERROR]: Cannot find namespace 'React'.
type WithChildrenIfReactComponentClass<C extends string | React.ComponentType<any>> = C extends React.ComponentClass<
                                                          ~~~~~
    at https://cdn.esm.sh/@types/styled-components@5.1.14/index.d.ts:97:59

TS2503 [ERROR]: Cannot find namespace 'React'.
type WithChildrenIfReactComponentClass<C extends string | React.ComponentType<any>> = C extends React.ComponentClass<
                                                                                                ~~~~~
    at https://cdn.esm.sh/@types/styled-components@5.1.14/index.d.ts:97:97

TS2503 [ERROR]: Cannot find namespace 'React'.
    ? { children?: React.ReactNode | undefined }
                   ~~~~~
    at https://cdn.esm.sh/@types/styled-components@5.1.14/index.d.ts:100:20

TS2503 [ERROR]: Cannot find namespace 'React'.
    C extends string | React.ComponentType<any>,
                       ~~~~~
    at https://cdn.esm.sh/@types/styled-components@5.1.14/index.d.ts:104:24

TS2503 [ERROR]: Cannot find namespace 'React'.
    AsC extends string | React.ComponentType<any> = C,
                         ~~~~~
    at https://cdn.esm.sh/@types/styled-components@5.1.14/index.d.ts:108:26

TS2503 [ERROR]: Cannot find namespace 'React'.
    FAsC extends string | React.ComponentType<any> = C
                          ~~~~~
    at https://cdn.esm.sh/@types/styled-components@5.1.14/index.d.ts:109:27

TS2503 [ERROR]: Cannot find namespace 'React'.
export interface GlobalStyleComponent<P, T> extends React.ComponentClass<ThemedGlobalStyledClassProps<P, T>> {}
                                                    ~~~~~
    at https://cdn.esm.sh/@types/styled-components@5.1.14/index.d.ts:129:53

TS2503 [ERROR]: Cannot find namespace 'React'.
type ForwardRefExoticBase<P> = Pick<React.ForwardRefExoticComponent<P>, keyof React.ForwardRefExoticComponent<any>>;
                                    ~~~~~
    at https://cdn.esm.sh/@types/styled-components@5.1.14/index.d.ts:137:37

TS2503 [ERROR]: Cannot find namespace 'React'.
type ForwardRefExoticBase<P> = Pick<React.ForwardRefExoticComponent<P>, keyof React.ForwardRefExoticComponent<any>>;
                                                                              ~~~~~
    at https://cdn.esm.sh/@types/styled-components@5.1.14/index.d.ts:137:79

TS2503 [ERROR]: Cannot find namespace 'JSX'.
    C extends keyof JSX.IntrinsicElements | React.ComponentType<any>,
                    ~~~
    at https://cdn.esm.sh/@types/styled-components@5.1.14/index.d.ts:154:21

TS2503 [ERROR]: Cannot find namespace 'React'.
    C extends keyof JSX.IntrinsicElements | React.ComponentType<any>,
                                            ~~~~~
    at https://cdn.esm.sh/@types/styled-components@5.1.14/index.d.ts:154:45

TS2503 [ERROR]: Cannot find namespace 'hoistNonReactStatics'.
        hoistNonReactStatics.NonReactStatics<C extends React.ComponentType<any> ? C : never>;
        ~~~~~~~~~~~~~~~~~~~~
    at https://cdn.esm.sh/@types/styled-components@5.1.14/index.d.ts:162:9

TS2503 [ERROR]: Cannot find namespace 'React'.
        hoistNonReactStatics.NonReactStatics<C extends React.ComponentType<any> ? C : never>;
                                                       ~~~~~
    at https://cdn.esm.sh/@types/styled-components@5.1.14/index.d.ts:162:56

TS2503 [ERROR]: Cannot find namespace 'React'.
    C extends string | React.ComponentType<any>,
                       ~~~~~
    at https://cdn.esm.sh/@types/styled-components@5.1.14/index.d.ts:165:24

TS2503 [ERROR]: Cannot find namespace 'React'.
    (props: StyledComponentProps<C, T, O, A> & { as?: never | undefined; forwardedAs?: never | undefined }): React.ReactElement<
                                                                                                             ~~~~~
    at https://cdn.esm.sh/@types/styled-components@5.1.14/index.d.ts:171:110

TS2503 [ERROR]: Cannot find namespace 'React'.
    <AsC extends string | React.ComponentType<any> = C, FAsC extends string | React.ComponentType<any> = AsC>(
                          ~~~~~
    at https://cdn.esm.sh/@types/styled-components@5.1.14/index.d.ts:174:27

TS2503 [ERROR]: Cannot find namespace 'React'.
    <AsC extends string | React.ComponentType<any> = C, FAsC extends string | React.ComponentType<any> = AsC>(
                                                                              ~~~~~
    at https://cdn.esm.sh/@types/styled-components@5.1.14/index.d.ts:174:79

TS2503 [ERROR]: Cannot find namespace 'React'.
    ): React.ReactElement<StyledComponentPropsWithAs<AsC, T, O, A, AsC, FAsC>>;
       ~~~~~
    at https://cdn.esm.sh/@types/styled-components@5.1.14/index.d.ts:176:8

TS2503 [ERROR]: Cannot find namespace 'JSX'.
    withComponent<WithC extends keyof JSX.IntrinsicElements | React.ComponentType<any>>(
                                      ~~~
    at https://cdn.esm.sh/@types/styled-components@5.1.14/index.d.ts:186:39

TS2503 [ERROR]: Cannot find namespace 'React'.
    withComponent<WithC extends keyof JSX.IntrinsicElements | React.ComponentType<any>>(
                                                              ~~~~~
    at https://cdn.esm.sh/@types/styled-components@5.1.14/index.d.ts:186:63

TS2503 [ERROR]: Cannot find namespace 'JSX'.
    C extends keyof JSX.IntrinsicElements | React.ComponentType<any>,
                    ~~~
    at https://cdn.esm.sh/@types/styled-components@5.1.14/index.d.ts:192:21

TS2503 [ERROR]: Cannot find namespace 'React'.
    C extends keyof JSX.IntrinsicElements | React.ComponentType<any>,
                                            ~~~~~
    at https://cdn.esm.sh/@types/styled-components@5.1.14/index.d.ts:192:45

TS2503 [ERROR]: Cannot find namespace 'JSX'.
    C extends keyof JSX.IntrinsicElements | React.ComponentType<any>,
                    ~~~
    at https://cdn.esm.sh/@types/styled-components@5.1.14/index.d.ts:215:21

TS2503 [ERROR]: Cannot find namespace 'React'.
    C extends keyof JSX.IntrinsicElements | React.ComponentType<any>,
                                            ~~~~~
    at https://cdn.esm.sh/@types/styled-components@5.1.14/index.d.ts:215:45

TS2503 [ERROR]: Cannot find namespace 'JSX'.
export type StyledFunction<C extends keyof JSX.IntrinsicElements | React.ComponentType<any>> = ThemedStyledFunction<
                                           ~~~
    at https://cdn.esm.sh/@types/styled-components@5.1.14/index.d.ts:236:44

TS2503 [ERROR]: Cannot find namespace 'React'.
export type StyledFunction<C extends keyof JSX.IntrinsicElements | React.ComponentType<any>> = ThemedStyledFunction<
                                                                   ~~~~~
    at https://cdn.esm.sh/@types/styled-components@5.1.14/index.d.ts:236:68

TS2503 [ERROR]: Cannot find namespace 'JSX'.
    [TTag in keyof JSX.IntrinsicElements]: ThemedStyledFunction<TTag, T>;
                   ~~~
    at https://cdn.esm.sh/@types/styled-components@5.1.14/index.d.ts:242:20

TS2503 [ERROR]: Cannot find namespace 'React'.
export type StyledComponentInnerComponent<C extends React.ComponentType<any>> = C extends StyledComponent<
                                                    ~~~~~
    at https://cdn.esm.sh/@types/styled-components@5.1.14/index.d.ts:245:53

TS2503 [ERROR]: Cannot find namespace 'JSX'.
    C extends keyof JSX.IntrinsicElements | React.ComponentType<any>
                    ~~~
    at https://cdn.esm.sh/@types/styled-components@5.1.14/index.d.ts:256:21

TS2503 [ERROR]: Cannot find namespace 'React'.
    C extends keyof JSX.IntrinsicElements | React.ComponentType<any>
                                            ~~~~~
    at https://cdn.esm.sh/@types/styled-components@5.1.14/index.d.ts:256:45

TS2503 [ERROR]: Cannot find namespace 'React'.
    ? React.ComponentPropsWithRef<StyledComponentInnerComponent<C>>
      ~~~~~
    at https://cdn.esm.sh/@types/styled-components@5.1.14/index.d.ts:258:7

TS2503 [ERROR]: Cannot find namespace 'React'.
    : React.ComponentPropsWithRef<C>;
      ~~~~~
    at https://cdn.esm.sh/@types/styled-components@5.1.14/index.d.ts:259:7

TS2503 [ERROR]: Cannot find namespace 'JSX'.
    <C extends keyof JSX.IntrinsicElements | React.ComponentType<any>>(
                     ~~~
    at https://cdn.esm.sh/@types/styled-components@5.1.14/index.d.ts:281:22

TS2503 [ERROR]: Cannot find namespace 'React'.
    <C extends keyof JSX.IntrinsicElements | React.ComponentType<any>>(
                                             ~~~~~
    at https://cdn.esm.sh/@types/styled-components@5.1.14/index.d.ts:281:46

TS2503 [ERROR]: Cannot find namespace 'React'.
    ThemeConsumer: React.Consumer<T>;
                   ~~~~~
    at https://cdn.esm.sh/@types/styled-components@5.1.14/index.d.ts:327:20

TS2503 [ERROR]: Cannot find namespace 'React'.
    ThemeContext: React.Context<T>;
                  ~~~~~
    at https://cdn.esm.sh/@types/styled-components@5.1.14/index.d.ts:328:19

TS2503 [ERROR]: Cannot find namespace 'React'.
export type BaseWithThemeFnInterface<T extends object> = <C extends React.ComponentType<any>>(
                                                                    ~~~~~
    at https://cdn.esm.sh/@types/styled-components@5.1.14/index.d.ts:342:69

TS2503 [ERROR]: Cannot find namespace 'React'.
    component: React.ComponentProps<C> extends { theme?: T | undefined } ? C : never,
               ~~~~~
    at https://cdn.esm.sh/@types/styled-components@5.1.14/index.d.ts:345:16

TS2503 [ERROR]: Cannot find namespace 'React'.
) => React.ForwardRefExoticComponent<WithOptionalTheme<React.ComponentPropsWithRef<C>, T>>;
     ~~~~~
    at https://cdn.esm.sh/@types/styled-components@5.1.14/index.d.ts:346:6

TS2503 [ERROR]: Cannot find namespace 'React'.
) => React.ForwardRefExoticComponent<WithOptionalTheme<React.ComponentPropsWithRef<C>, T>>;
                                                       ~~~~~
    at https://cdn.esm.sh/@types/styled-components@5.1.14/index.d.ts:346:56

TS2503 [ERROR]: Cannot find namespace 'React'.
    children?: React.ReactNode | undefined;
               ~~~~~
    at https://cdn.esm.sh/@types/styled-components@5.1.14/index.d.ts:362:16

TS2503 [ERROR]: Cannot find namespace 'React'.
export type BaseThemeProviderComponent<T extends object, U extends object = T> = React.ComponentClass<
                                                                                 ~~~~~
    at https://cdn.esm.sh/@types/styled-components@5.1.14/index.d.ts:365:82

TS2503 [ERROR]: Cannot find namespace 'React'.
export const ThemeContext: React.Context<AnyIfEmpty<DefaultTheme>>;
                           ~~~~~
    at https://cdn.esm.sh/@types/styled-components@5.1.14/index.d.ts:374:28

TS2503 [ERROR]: Cannot find namespace 'React'.
    collectStyles(tree: React.ReactNode): React.ReactElement<{ sheet: ServerStyleSheet }>;
                        ~~~~~
    at https://cdn.esm.sh/@types/styled-components@5.1.14/index.d.ts:394:25

TS2503 [ERROR]: Cannot find namespace 'React'.
    collectStyles(tree: React.ReactNode): React.ReactElement<{ sheet: ServerStyleSheet }>;
                                          ~~~~~
    at https://cdn.esm.sh/@types/styled-components@5.1.14/index.d.ts:394:43

TS2503 [ERROR]: Cannot find namespace 'React'.
    getStyleElement(): Array<React.ReactElement<{}>>;
                             ~~~~~
    at https://cdn.esm.sh/@types/styled-components@5.1.14/index.d.ts:397:30

TS2304 [ERROR]: Cannot find name 'HTMLElement'.
    target?: HTMLElement | undefined;
             ~~~~~~~~~~~
    at https://cdn.esm.sh/@types/styled-components@5.1.14/index.d.ts:418:14

Found 58 errors.
```

**Comment by ije** [comment]
seems it is the types issues, pls use `?no-check` instead, i will look into it ASAP!

**Comment by talentlessguy** [comment]
works fine on v55
