### ISSUE TITLE
Failed to import - @apollo/client

### ISSUE THREAD

**Issue by talentlessguy** [alephjs/esm.sh#162]
## Failing module

```js
import * as mod from 'https://esm.sh/@apollo/client'
```

## Error message

After running `deno run` I get this:

```
error: TS2749 [ERROR]: 'Observable' refers to a value, but is being used as a type here. Did you mean 'typeof Observable'?
    at https://cdn.esm.sh/v53/@apollo/client@3.4.13/utilities/observables/asyncMap.d.ts:3:52

TS2749 [ERROR]: 'Observable' refers to a value, but is being used as a type here. Did you mean 'typeof Observable'?
    at https://cdn.esm.sh/v53/@apollo/client@3.4.13/utilities/observables/asyncMap.d.ts:3:155

TS2749 [ERROR]: 'Observable' refers to a value, but is being used as a type here. Did you mean 'typeof Observable'?
declare type Source<T> = MaybeAsync<Observable<T>>;
                                    ~~~~~~~~~~
    at https://cdn.esm.sh/v53/@apollo/client@3.4.13/utilities/observables/Concast.d.ts:4:37

TS2749 [ERROR]: 'Observable' refers to a value, but is being used as a type here. Did you mean 'typeof Observable'?
export declare function fixObservableSubclass<S extends new (...args: any[]) => Observable<any>>(subclass: S): S;
                                                                                ~~~~~~~~~~
    at https://cdn.esm.sh/v53/@apollo/client@3.4.13/utilities/observables/subclassing.d.ts:3:81

TS2749 [ERROR]: 'Observable' refers to a value, but is being used as a type here. Did you mean 'typeof Observable'?
export declare type NextLink = (operation: Operation) => Observable<FetchResult>;
                                                         ~~~~~~~~~~
    at https://cdn.esm.sh/v53/@apollo/client@3.4.13/link/core/types.d.ts:27:58

TS2749 [ERROR]: 'Observable' refers to a value, but is being used as a type here. Did you mean 'typeof Observable'?
export declare type RequestHandler = (operation: Operation, forward: NextLink) => Observable<FetchResult> | null;
                                                                                  ~~~~~~~~~~
    at https://cdn.esm.sh/v53/@apollo/client@3.4.13/link/core/types.d.ts:28:83

TS2749 [ERROR]: 'Observable' refers to a value, but is being used as a type here. Did you mean 'typeof Observable'?
    static execute(link: ApolloLink, operation: GraphQLRequest): Observable<FetchResult>;
                                                                 ~~~~~~~~~~
    at https://cdn.esm.sh/v53/@apollo/client@3.4.13/link/core/ApolloLink.d.ts:8:66

TS2749 [ERROR]: 'Observable' refers to a value, but is being used as a type here. Did you mean 'typeof Observable'?
    request(operation: Operation, forward?: NextLink): Observable<FetchResult> | null;
                                                       ~~~~~~~~~~
    at https://cdn.esm.sh/v53/@apollo/client@3.4.13/link/core/ApolloLink.d.ts:13:56

TS2304 [ERROR]: Cannot find name 'WindowOrWorkerGlobalScope'.
    fetch?: WindowOrWorkerGlobalScope['fetch'];
            ~~~~~~~~~~~~~~~~~~~~~~~~~
    at https://cdn.esm.sh/v53/@apollo/client@3.4.13/link/http/selectHttpOptionsAndBody.d.ts:14:13

TS2304 [ERROR]: Cannot find name 'WindowOrWorkerGlobalScope'.
export declare const checkFetcher: (fetcher: WindowOrWorkerGlobalScope['fetch'] | undefined) => void;
                                             ~~~~~~~~~~~~~~~~~~~~~~~~~
    at https://cdn.esm.sh/v53/@apollo/client@3.4.13/link/http/checkFetcher.d.ts:1:46

TS2749 [ERROR]: 'Observable' refers to a value, but is being used as a type here. Did you mean 'typeof Observable'?
export declare function fromError<T>(errorValue: any): Observable<T>;
                                                       ~~~~~~~~~~
    at https://cdn.esm.sh/v53/@apollo/client@3.4.13/link/utils/fromError.d.ts:3:56

TS2749 [ERROR]: 'Observable' refers to a value, but is being used as a type here. Did you mean 'typeof Observable'?
export declare function toPromise<R>(observable: Observable<R>): Promise<R>;
                                                 ~~~~~~~~~~
    at https://cdn.esm.sh/v53/@apollo/client@3.4.13/link/utils/toPromise.d.ts:3:50

TS2749 [ERROR]: 'Observable' refers to a value, but is being used as a type here. Did you mean 'typeof Observable'?
export declare function fromPromise<T>(promise: Promise<T>): Observable<T>;
                                                             ~~~~~~~~~~
    at https://cdn.esm.sh/v53/@apollo/client@3.4.13/link/utils/fromPromise.d.ts:3:62

TS2749 [ERROR]: 'Observable' refers to a value, but is being used as a type here. Did you mean 'typeof Observable'?
    startGraphQLSubscription<T = any>({ query, fetchPolicy, errorPolicy, variables, context, }: SubscriptionOptions): Observable<FetchResult<T>>;
                                                                                                                      ~~~~~~~~~~
    at https://cdn.esm.sh/v53/@apollo/client@3.4.13/core/QueryManager.d.ts:103:119

TS2749 [ERROR]: 'Observable' refers to a value, but is being used as a type here. Did you mean 'typeof Observable'?
    subscribe<T = any, TVariables = OperationVariables>(options: SubscriptionOptions<TVariables, T>): Observable<FetchResult<T>>;
                                                                                                      ~~~~~~~~~~
    at https://cdn.esm.sh/v53/@apollo/client@3.4.13/core/ApolloClient.d.ts:54:103

TS2749 [ERROR]: 'Observable' refers to a value, but is being used as a type here. Did you mean 'typeof Observable'?
    __requestRaw(payload: GraphQLRequest): Observable<ExecutionResult>;
                                           ~~~~~~~~~~
    at https://cdn.esm.sh/v53/@apollo/client@3.4.13/core/ApolloClient.d.ts:60:44

TS2749 [ERROR]: 'Observable' refers to a value, but is being used as a type here. Did you mean 'typeof Observable'?
    query?: Observable<any>;
            ~~~~~~~~~~
    at https://cdn.esm.sh/v53/@apollo/client@3.4.13/react/types/types.d.ts:125:13

Found 17 errors.
```

## Additional info

- **esm.sh version**: v53
- **Deno version**: 1.14

**Comment by ije** [comment]
@talentlessguy thanks for report!

**Comment by ije** [comment]
transform types for Deno is kind of pain for me now 🤣

**Comment by talentlessguy** [comment]
@ije sorry to hear that :/

i just report every package that has problematic types

**Comment by ije** [comment]
no worries, i appreciate that and i will fix it asap, thanks a lot @talentlessguy

**Comment by talentlessguy** [comment]
works smoothly in v53, closing
