### ISSUE TITLE
Failed to import rxjs via ionic@cli

### ISSUE THREAD

**Issue by rotu** [alephjs/esm.sh#169]
## Failing module

- **npm**: https://www.npmjs.com/package/rxjs
- **npm**: https://www.npmjs.com/package/@ionic/cli

```sh
deno run http://esm.sh/@ionic/cli
```

## Error message

```
Download https://cdn.esm.sh/error.js?type=unsupported-nodejs-builtin-module&name=worker_threads&importer=write-file-atomic
Download https://cdn.esm.sh/error.js?type=unsupported-nodejs-builtin-module&name=dns&importer=socks-proxy-agent
Download https://cdn.esm.sh/v53/rxjs@7.3.0/index.d.ts
Download https://cdn.esm.sh/error.js?type=unsupported-nodejs-builtin-module&name=dns&importer=pac-resolver
error: Import 'https://cdn.esm.sh/error.js?type=unsupported-nodejs-builtin-module&name=worker_threads&importer=write-file-atomic' failed: 500 Internal Server Error
    at https://cdn.esm.sh/v53/write-file-atomic@3.0.3/deno/write-file-atomic.js:2:186
```

## Additional info

- **esm.sh version**: v53
- **Deno version**: 1.14.1

**Comment by talentlessguy** [comment]
getting this on v55:

```sh
➜ deno run http://esm.sh/@ionic/cli

Download https://cdn.esm.sh/error.js?type=unsupported-nodejs-builtin-module&name=worker_threads&importer=write-file-atomic
Download https://cdn.esm.sh/v55/rxjs@7.4.0/index.d.ts
error: Relative import path "readline" not prefixed with / or ./ or ../ from "https://cdn.esm.sh/v55/@types/node/readline.d.ts"
    at https://cdn.esm.sh/v55/write-file-atomic@3.0.3/deno/write-file-atomic.js:2:233
```
