### ISSUE TITLE
Random imports broken on CI/CD

### ISSUE THREAD

**Issue by akaFTS** [alephjs/esm.sh#181]
I'm using GitHub Actions to build my Aleph app to a SSG and deploy it to GitHub pages. However, the build phase is failing due to broken imports that change from run to run - already seen react-dom, recharts, and now font-awesome:

```
ERROR swc: Unexpected eof at https://cdn.esm.sh/v53/@fortawesome/free-brands-svg-icons@5.15.4/deno/free-brands-svg-icons.js:2:114599
error: Uncaught (in promise) RuntimeError: unreachable
    at <anonymous> (wasm://wasm/01af0e1a:1:5988112)
    at <anonymous> (wasm://wasm/01af0e1a:1:6080963)
    at <anonymous> (wasm://wasm/01af0e1a:1:6153071)
    at <anonymous> (wasm://wasm/01af0e1a:1:6148359)
    at <anonymous> (wasm://wasm/01af0e1a:1:6153171)
    at <anonymous> (wasm://wasm/01af0e1a:1:6100310)
    at <anonymous> (wasm://wasm/01af0e1a:1:3790639)
    at <anonymous> (wasm://wasm/01af0e1a:1:3987607)
    at <anonymous> (wasm://wasm/01af0e1a:1:6138696)
    at transformSync (https://deno.land/x/aleph@v0.3.0-beta.15/compiler/dist/compiler.js:196:18)
```

I didn't manage to grab one of those unparseable modules to verify what exactly is causing the EOF error.

**Comment by ije** [comment]
closed in https://github.com/alephjs/aleph.js/commit/e51fabe76f4abedbb7c4549e4eda8b3ede2d2379
