### ISSUE TITLE
Failed to import - monaco-editor@0.29.1/esm/vs/editor/editor.worker

### ISSUE THREAD

**Issue by uki00a** [alephjs/esm.sh#198]
## Failing module

- **npm**: `monaco-editor@0.29.1`

```js
import EditorWorker from "https://esm.sh/monaco-editor@0.29.1/esm/vs/editor/editor.worker?worker";
const worker = new EditorWorker();
```

## Error message

After running `deno run` I get this:

```
Download https://esm.sh/monaco-editor@0.29.1/esm/vs/editor/editor.worker?worker
error: Uncaught URIError: invalid URL: relative URL without a base
  return new Worker('/v55/monaco-editor@0.29.1/deno/esm/vs/editor/editor.worker.js', { type: 'module' })
                                                                                                                         ^
    at Object.opSync (deno:core/01_core.js:138:12)
    at createWorker (deno:runtime/js/11_workers.js:31:17)
    at new Worker (deno:runtime/js/11_workers.js:115:18)
    at new WorkerWrapper (https://esm.sh/monaco-editor@0.29.1/esm/vs/editor/editor.worker?worker:3:10)
    at file:///home/uki00a/ghq/github.com/uki00a/deno-weekly/sample.js:2:16
```

## Additional info

- **esm.sh version**: v55
- **Deno version**: 1.15.3

**Comment by ije** [comment]
@uki00a thanks, i just fixed the import url, but seems the `monaco-editor` workers can not run in deno, something is `undefined`
<img width="807" alt="Screenshot 2021-10-31 at 18 14 23" src="https://user-images.githubusercontent.com/2883484/139577844-5307992a-2501-440f-9ef3-8958cd60e6d3.png">
