### ISSUE TITLE
Failed to import - @supabase/supabase-js

### ISSUE THREAD

**Issue by roseMix** [alephjs/esm.sh#204]
## Failing module

- **GitHub**: https://github.com/supabase/supabase-js
- **npm**: https://www.npmjs.com/package/@supabase/supabase-js

```js
import { createClient } from "https://esm.sh/@supabase/supabase-js"
```

## Error message

After running `deno run` I get this:

```
error: Relative import path "@supabase/gotrue-js" not prefixed with / or ./ or ../ from "https://cdn.esm.sh/v57/@supabase/supabase-js@1.25.2/dist/main/lib/types.d.ts"
```

## Additional info

- **esm.sh version**: v57
- **Deno version**: 1.15.3

**Comment by ije** [comment]
@roseMix try `?no-check` argument, i'll look into it! thanks

**Comment by roseMix** [comment]
Thanks @ije works to get by original error, but now I'm getting this:

```
ReferenceError: XMLHttpRequest is not defined
    at https://cdn.esm.sh/v57/cross-fetch@3.1.4/deno/cross-fetch.js:2:7654
    at new Promise (<anonymous>)
    at _ (https://cdn.esm.sh/v57/cross-fetch@3.1.4/deno/cross-fetch.js:2:7522)
    at https://cdn.esm.sh/v57/@supabase/gotrue-js@1.19.0/deno/gotrue-js.js:2:861
    at new Promise (<anonymous>)
    at https://cdn.esm.sh/v57/@supabase/gotrue-js@1.19.0/deno/gotrue-js.js:2:841
    at Generator.next (<anonymous>)
    at https://cdn.esm.sh/v57/@supabase/gotrue-js@1.19.0/deno/gotrue-js.js:2:356
    at new Promise (<anonymous>)
    at y (https://cdn.esm.sh/v57/@supabase/gotrue-js@1.19.0/deno/gotrue-js.js:2:153)
```

As far as I know there no known polyfill for `XMLHttpRequest` so I assume it's just unfixable at this point.

Thanks anyways!

**Comment by wangbinyq** [comment]
> Thanks @ije works to get by original error, but now I'm getting this:
> 
> ```
> ReferenceError: XMLHttpRequest is not defined
>     at https://cdn.esm.sh/v57/cross-fetch@3.1.4/deno/cross-fetch.js:2:7654
>     at new Promise (<anonymous>)
>     at _ (https://cdn.esm.sh/v57/cross-fetch@3.1.4/deno/cross-fetch.js:2:7522)
>     at https://cdn.esm.sh/v57/@supabase/gotrue-js@1.19.0/deno/gotrue-js.js:2:861
>     at new Promise (<anonymous>)
>     at https://cdn.esm.sh/v57/@supabase/gotrue-js@1.19.0/deno/gotrue-js.js:2:841
>     at Generator.next (<anonymous>)
>     at https://cdn.esm.sh/v57/@supabase/gotrue-js@1.19.0/deno/gotrue-js.js:2:356
>     at new Promise (<anonymous>)
>     at y (https://cdn.esm.sh/v57/@supabase/gotrue-js@1.19.0/deno/gotrue-js.js:2:153)
> ```
> 
> As far as I know there no known polyfill for `XMLHttpRequest` so I assume it's just unfixable at this point.
> 
> Thanks anyways!

There is a package called xhr on https://deno.land/x/xhr

**Comment by ije** [comment]
now we add the `xhr` polyfill automatically for `corss-fetch`
