### ISSUE TITLE
Failed to import - ipfs-http-client

### ISSUE THREAD

**Issue by talentlessguy** [alephjs/esm.sh#219]
## Failing module

- **GitHub**: https://github.com/ipfs/js-ipfs/tree/master/packages/ipfs-http-client
- **npm**: https://npm.im/ipfs-http-client

```js
import { create } from 'https://esm.sh/ipfs-http-client'
```

## Error message

After running `deno run` I get this:

```
Download https://cdn.esm.sh/v58/ipfs-utils@9.0.2/src/files/glob-source.js~.d.ts
Download https://cdn.esm.sh/v58/ipfs-utils@9.0.2/src/files/url-source.js~.d.ts
Download https://cdn.esm.sh/v58/multiformats@9.4.10/bases/interface~.d.ts
Download https://cdn.esm.sh/v58/multiformats@9.4.10/cid~.d.ts
Download https://cdn.esm.sh/v58/multiformats@9.4.10/codecs/interface~.d.ts
Download https://cdn.esm.sh/v58/multiformats@9.4.10/hashes/interface~.d.ts
Download https://cdn.esm.sh/error.js?type=unsupported-nodejs-builtin-module&name=worker_threads&importer=fetch-blob
Check a generated module
warning: Cannot load module "https://deno.land/std@0.115.0/node/crypto.ts".
    at https://cdn.esm.sh/v58/nanoid@3.1.30/deno/nanoid.js:2:72
  If the source module contains only types, use `import type` and `export type` to import it instead.
warning: Cannot load module "https://deno.land/std@0.115.0/node/stream.ts".
    at https://cdn.esm.sh/v58/browserify-zlib@0.2.0/deno/browserify-zlib.bundle.js:2:292
  If the source module contains only types, use `import type` and `export type` to import it instead.
warning: Cannot load module "https://deno.land/std@0.115.0/node/events.ts".
    at https://cdn.esm.sh/v58/stream-http@3.2.0/deno/stream-http.bundle.js:2:242
  If the source module contains only types, use `import type` and `export type` to import it instead.
warning: Cannot load module "https://deno.land/std@0.115.0/node/string_decoder.ts".
    at https://cdn.esm.sh/v58/stream-http@3.2.0/deno/stream-http.bundle.js:2:419
  If the source module contains only types, use `import type` and `export type` to import it instead.
warning: Cannot load module "https://deno.land/std@0.115.0/node/net.ts".
    at https://cdn.esm.sh/v58/node-fetch@3.1.0/deno/node-fetch.js:3:12429
  If the source module contains only types, use `import type` and `export type` to import it instead.
warning: Cannot load module "https://deno.land/std@0.115.0/node/path.ts".
    at https://cdn.esm.sh/v58/fetch-blob@3.1.3/deno/from.js:2:1906
  If the source module contains only types, use `import type` and `export type` to import it instead.
warning: Cannot load module "https://deno.land/std@0.115.0/node/fs.ts".
    at https://cdn.esm.sh/v58/fetch-blob@3.1.3/deno/from.js:2:1838
  If the source module contains only types, use `import type` and `export type` to import it instead.
warning: Cannot load module "https://deno.land/std@0.115.0/node/querystring.ts".
    at https://cdn.esm.sh/v58/url@0.11.0/deno/url.bundle.js:2:28
  If the source module contains only types, use `import type` and `export type` to import it instead.
warning: Cannot load module "https://deno.land/std@0.115.0/node/assert.ts".
    at https://cdn.esm.sh/v58/browserify-zlib@0.2.0/deno/browserify-zlib.bundle.js:2:164
  If the source module contains only types, use `import type` and `export type` to import it instead.
error: Relative import path "http" not prefixed with / or ./ or ../ from "https://cdn.esm.sh/v58/@types/node/http.d.ts"
    at https://cdn.esm.sh/v58/fetch-blob@3.1.3/deno/from.js:2:1982
```

## Additional info

- **esm.sh version**: v58
- **Deno version**:  1.16.2

**Comment by talentlessguy** [comment]
@ije could you please `worker_threads` from deno std to make this module work?
