### ISSUE TITLE
Failed to import - react-fontawesome imports `cdn.esm.shreact`

### ISSUE THREAD

**Issue by crowlKats** [alephjs/esm.sh#241]
## Failing module

- **GitHub**: https://github.com/FortAwesome/react-fontawesome
- **npm**: https://www.npmjs.com/package/@fortawesome/react-fontawesome

```js
import { FontAwesomeIcon } from 'https://esm.sh/@fortawesome/react-fontawesome@0.1.14'
```

## Error message

After running `deno run` I get this:

```
/* your error log here */
Download https://cdn.esm.shreact/
error: AssertionError: "data" is unexpectedly null for "https://cdn.esm.shreact/".
```
The AssertionError is "expected", as tsc isn't emitting something that it is expected

## Additional info

- **esm.sh version**: v59
- **Deno version**: 1.17.1

**Comment by ije** [comment]
I can not repeat it, more details?

<img width="894" alt="Screen Shot 2022-01-05 at 15 11 33" src="https://user-images.githubusercontent.com/2883484/148175387-552ac477-efc6-4d0a-ad52-89391f7ec9d1.png">

**Comment by talentlessguy** [comment]
works fine on v61:

```
➜ deno eval --unstable "import { FontAwesomeIcon } from 'https://esm.sh/@fortawesome/react-fontawesome@0.1.14'"
Download https://esm.sh/@fortawesome/react-fontawesome@0.1.14
Download https://cdn.esm.sh/v61/@fortawesome/react-fontawesome@0.1.14/deno/react-fontawesome.js
Download https://cdn.esm.sh/v61/@fortawesome/react-fontawesome@0.1.14/index.d.ts
Download https://cdn.esm.sh/v61/@fortawesome/fontawesome-svg-core@1.3.0-beta3/deno/fontawesome-svg-core.js
Download https://cdn.esm.sh/v61/prop-types@15.8.0/deno/prop-types.js
Download https://cdn.esm.sh/v61/@fortawesome/fontawesome-svg-core@1.2.36/index.d.ts
Download https://cdn.esm.shreact/
Download https://cdn.esm.sh/v61/@fortawesome/fontawesome-common-types@0.2.36/index.d.ts
```

**Comment by crowlKats** [comment]
Sorry for the late reply. Please try to run it in a ts file, or eval with ts, not repl or standard eval

**Comment by talentlessguy** [comment]
ok I see now:

```
➜ deno eval --ext=ts "import { FontAwesomeIcon } from 'https://esm.sh/@fortawesome/react-fontawesome@0.1.14'"
Download https://cdn.esm.shreact/
error: AssertionError: "data" is unexpectedly null for "https://cdn.esm.shreact/".
    at assert (deno:cli/tsc/99_main_compiler.js:71:13)
    at Object.getSourceFile (deno:cli/tsc/99_main_compiler.js:289:7)
    at findSourceFileWorker (deno:cli/tsc/00_typescript.js:115354:29)
    at findSourceFile (deno:cli/tsc/00_typescript.js:115263:26)
    at deno:cli/tsc/00_typescript.js:115215:85
    at getSourceFileFromReferenceWorker (deno:cli/tsc/00_typescript.js:115199:77)
    at processSourceFile (deno:cli/tsc/00_typescript.js:115215:13)
    at deno:cli/tsc/00_typescript.js:115506:17
    at Object.forEach (deno:cli/tsc/00_typescript.js:391:30)
    at processReferencedFiles (deno:cli/tsc/00_typescript.js:115505:16)

```

**Comment by ije** [comment]
i guess it is **types** problem, i will look into it.

**Comment by crowlKats** [comment]
Found another case of this: https://esm.sh/@tensorflow/tfjs-backend-webgpu 
somewhere deep within it will try to import https://cdn.esm.shwebgl2/
