### ISSUE TITLE
Failed to import -

### ISSUE THREAD

**Issue by firstdorsal** [alephjs/esm.sh#243]
## Failing module

- **GitHub**:  https://github.com/bcherny/json-schema-to-typescript
- **npm**: https://www.npmjs.com/package/json-schema-to-typescript

```js
export { compile } from "https://esm.sh/json-schema-to-typescript?bundle";
```

## Error message

After running `deno run` I get this:

```
deno run --allow-read main.ts
Download https://cdn.esm.sh/v54/deno_std_node_fs.js
Download https://cdn.esm.sh/v54/deno_std_node_path.js
Download https://cdn.esm.sh/v54/deno_std_node_querystring.js
Download https://cdn.esm.sh/v54/deno_std_node_events.js
error: Import 'https://cdn.esm.sh/v54/deno_std_node_fs.js' failed, not found.
    at https://cdn.esm.sh/v54/json-schema-to-typescript@10.1.5/deno/json-schema-to-typescript.bundle.js:2:249
```

## Additional info

- **esm.sh version**: v54 or v59?
- **Deno version**: 
deno 1.17.0 (release, x86_64-unknown-linux-gnu)
v8 9.7.106.15
typescript 4.5.2

**Comment by talentlessguy** [comment]
try to add `?pin=v60` in the end

**Comment by talentlessguy** [comment]
seems to be working for me:

```sh
deno eval --unstable 'import { compile } from "https://esm.sh/json-schema-to-typescript?bundle&pin=v60"'
```

**Comment by firstdorsal** [comment]
Thank you!
The import works but when trying to compile a json schema to ts it throws:
```sh
error: Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'href')
    at Object.Jn.cwd (https://cdn.esm.sh/v60/json-schema-to-typescript@10.1.5/deno/json-schema-to-typescript.bundle.js:203:2375)
    at Mi.parse (https://cdn.esm.sh/v60/json-schema-to-typescript@10.1.5/deno/json-schema-to-typescript.bundle.js:241:7503)
    at Mi.resolve (https://cdn.esm.sh/v60/json-schema-to-typescript@10.1.5/deno/json-schema-to-typescript.bundle.js:241:8391)
    at Mi.dereference (https://cdn.esm.sh/v60/json-schema-to-typescript@10.1.5/deno/json-schema-to-typescript.bundle.js:241:9061)
    at Object.<anonymous> (https://cdn.esm.sh/v60/json-schema-to-typescript@10.1.5/deno/json-schema-to-typescript.bundle.js:241:11076)
    at k (https://cdn.esm.sh/v60/json-schema-to-typescript@10.1.5/deno/json-schema-to-typescript.bundle.js:241:10666)
    at Object.next (https://cdn.esm.sh/v60/json-schema-to-typescript@10.1.5/deno/json-schema-to-typescript.bundle.js:241:9970)
    at https://cdn.esm.sh/v60/json-schema-to-typescript@10.1.5/deno/json-schema-to-typescript.bundle.js:241:9674
    at new Promise (<anonymous>)
    at Cce (https://cdn.esm.sh/v60/json-schema-to-typescript@10.1.5/deno/json-schema-to-typescript.bundle.js:241:9471)
```

I already tried `console.log(await jstt.compile(schemaJSON, "Input", { cwd: Deno.cwd() }));` to set the cwd with deno instead of the default `process.cwd()`

**Comment by ije** [comment]
plz try to run deno with `--location=https://localhost` option

**Comment by firstdorsal** [comment]
thanks!

this worked:
```ts
console.log(await jstt.compile(schemaJSON, "Input", { cwd: Deno.cwd(), format: false }));
```
