### ISSUE TITLE
Error with `stripe` package

### ISSUE THREAD

**Issue by aegooby** [alephjs/esm.sh#42]
Using the `https://esm.sh/stripe` package gives the error,
```
error: TS2439 [ERROR]: Import or export declaration in an ambient module declaration cannot reference module through relative module name.
    export * from '/v33/@types/node@14.14.37/http.d.ts';
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    at https://cdn.esm.sh/v33/@types/node@14.14.37/http.d.ts:2:5

TS2439 [ERROR]: Import or export declaration in an ambient module declaration cannot reference module through relative module name.
    import * as stream from '/v33/node:stream';
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    at https://cdn.esm.sh/v33/@types/node@14.14.37/http.d.ts:6:5

TS2439 [ERROR]: Import or export declaration in an ambient module declaration cannot reference module through relative module name.
    import { URL } from '/v33/node:url';
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    at https://cdn.esm.sh/v33/@types/node@14.14.37/http.d.ts:7:5

TS2439 [ERROR]: Import or export declaration in an ambient module declaration cannot reference module through relative module name.
    import { Socket, Server as NetServer } from '/v33/node:net';
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    at https://cdn.esm.sh/v33/@types/node@14.14.37/http.d.ts:8:5
```
Trying with `https://esm.sh/stripe?no-check` gives,
```
error: Uncaught ReferenceError: require is not defined
    at https://cdn.esm.sh/v33/stripe@8.141.0/deno/stripe.js:4:12741
    at https://cdn.esm.sh/v33/stripe@8.141.0/deno/stripe.js:1:763
    at https://cdn.esm.sh/v33/stripe@8.141.0/deno/stripe.js:4:23152
    at https://cdn.esm.sh/v33/stripe@8.141.0/deno/stripe.js:1:763
    at https://cdn.esm.sh/v33/stripe@8.141.0/deno/stripe.js:4:29463
    at https://cdn.esm.sh/v33/stripe@8.141.0/deno/stripe.js:1:763
    at https://cdn.esm.sh/v33/stripe@8.141.0/deno/stripe.js:5:10580
    at https://cdn.esm.sh/v33/stripe@8.141.0/deno/stripe.js:1:763
    at https://cdn.esm.sh/v33/stripe@8.141.0/deno/stripe.js:5:15340
    at https://cdn.esm.sh/v33/stripe@8.141.0/deno/stripe.js:1:763
```

**Comment by ije** [comment]
stripe is using the `child_process` that is not supported by deno currently

**Comment by aegooby** [comment]
According to [this issue](https://github.com/stripe/stripe-node/issues/997) and [this pull request](https://github.com/stripe/stripe-node/pull/775) in the Stripe repository it seems that they are moving towards removing the dependency on `child_process` so it can be used in CloudFlare workers, which has API similar to Deno with regards to Stripe according to the maintainers. It seems the only thing left is Node `http`/`https` either being polyfilled or converted to use `fetch()` instead.

I am uneducated on the process of converting modules to Deno, but seeing as the Stripe package is important to my projects I am willing to help out with the porting if needed.

**Comment by talentlessguy** [comment]
still happens on v47

```
Check file:///tmp/test.ts
error: TS2439 [ERROR]: Import or export declaration in an ambient module declaration cannot reference module through relative module name.
    import * as stream from '/v47/node:stream';
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    at https://cdn.esm.sh/v47/@types/node@16.7.10/http.d.ts:43:5

TS2439 [ERROR]: Import or export declaration in an ambient module declaration cannot reference module through relative module name.
    import { URL } from '/v47/node:url';
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    at https://cdn.esm.sh/v47/@types/node@16.7.10/http.d.ts:44:5

TS2439 [ERROR]: Import or export declaration in an ambient module declaration cannot reference module through relative module name.
    import { Socket, Server as NetServer } from '/v47/node:net';
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    at https://cdn.esm.sh/v47/@types/node@16.7.10/http.d.ts:45:5

TS2439 [ERROR]: Import or export declaration in an ambient module declaration cannot reference module through relative module name.
    export * from '/v47/@types/node@16.7.10/http.d.ts';
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    at https://cdn.esm.sh/v47/@types/node@16.7.10/http.d.ts:1357:5
```

**Comment by ije** [comment]
https://esm.sh/stripe?no-check should work

**Comment by ije** [comment]
I will check the types transformer

**Comment by talentlessguy** [comment]
seems to work fine in v53

feel free to reopen if it persists
